//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_quest3 : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.quest3_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerValue
        {
            get
            {
                return SteamVR_Actions.quest3_TriggerValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.quest3_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single GripValue
        {
            get
            {
                return SteamVR_Actions.quest3_GripValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.quest3_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.quest3_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickClick
        {
            get
            {
                return SteamVR_Actions.quest3_ThumbstickClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Thumbstick
        {
            get
            {
                return SteamVR_Actions.quest3_Thumbstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.quest3_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.quest3_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.quest3_Haptic;
            }
        }
    }
}
